[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
auto_detect_solc = true

optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000

[invariant]
depth = 20
runs = 1000
fail_on_revert = true
shrink_run_limit = 0

[rpc_endpoints]
blast_sepolia = "${BLAST_SEPOLIA_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_URL}"
blast = "${BLAST_MAINNET_URL}"
mainnet = "${ETHEREUM_MAINNET_URL}"

[etherscan]
blast_sepolia = { key = "${BLASTSCAN_API_KEY}", url = "https://api-sepolia.blastscan.io/api", chain = 168587773 }
blast = { key = "${BLASTSCAN_API_KEY}", url = "https://api.blastscan.io/api/" }